// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB3aKosQOnLDaqn0aeWdkBYJo1FUChMCqw',
    appId: '1:866143547897:web:87af08462de6c7490a8d28',
    messagingSenderId: '866143547897',
    projectId: 'lianaplant-5dcd8',
    authDomain: 'lianaplant-5dcd8.firebaseapp.com',
    storageBucket: 'lianaplant-5dcd8.appspot.com',
    measurementId: 'G-N9FL9L00N0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA4fiqyHt8hGIXE_SIyIXrFXbzSks9xyZY',
    appId: '1:866143547897:android:57a2de506be0ce280a8d28',
    messagingSenderId: '866143547897',
    projectId: 'lianaplant-5dcd8',
    storageBucket: 'lianaplant-5dcd8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBWg3RVEAGn9d4uIZIGDECuubAQ7aij9V8',
    appId: '1:866143547897:ios:7bbc6a85283f0ad80a8d28',
    messagingSenderId: '866143547897',
    projectId: 'lianaplant-5dcd8',
    storageBucket: 'lianaplant-5dcd8.appspot.com',
    iosBundleId: 'com.example.lianaPlant',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBWg3RVEAGn9d4uIZIGDECuubAQ7aij9V8',
    appId: '1:866143547897:ios:7bbc6a85283f0ad80a8d28',
    messagingSenderId: '866143547897',
    projectId: 'lianaplant-5dcd8',
    storageBucket: 'lianaplant-5dcd8.appspot.com',
    iosBundleId: 'com.example.lianaPlant',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB3aKosQOnLDaqn0aeWdkBYJo1FUChMCqw',
    appId: '1:866143547897:web:a9bb4c0e69561e480a8d28',
    messagingSenderId: '866143547897',
    projectId: 'lianaplant-5dcd8',
    authDomain: 'lianaplant-5dcd8.firebaseapp.com',
    storageBucket: 'lianaplant-5dcd8.appspot.com',
    measurementId: 'G-2YNFK7T841',
  );
}
